name: Deploy to Azure
on:
  push: { branches: [main] }

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: "88b988d0-d70b-4a8e-b7d8-50c4b3da7bff"
          tenant-id: "fdd066e1-ee37-49bc-b08f-d0e152119b04"
          subscription-id: "764cc28a-0e45-4d5b-aca7-a1baf16a334b"
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage blob download \
            --account-name iamazurelab39f82a4ba \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
